steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/DimitriDerthe/puppeteer-gcp-cloudfunctions.git']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'functions', 'deploy', 'prod-belgium', '--trigger-http', '--memory=1024M', '--runtime=nodejs8', '--region=europe-west1', '--entry-point=webcheck', '--set-env-vars', 'getTrace=false']
