steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/DimitriDerthe/puppeteer-gcp-cloudfunctions.git']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'functions', 'deploy', 'webcheck', '--trigger-http', '--memory=1024M']